server:
  port: 8080

spring:
  application:
    name: SpringAuthCore

  datasource:
    url: jdbc:h2:./data/tempDB
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        connection:
          CharSet: utf-8
          characterEncoding: utf-8
          useUnicode: true

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt_secret_key: 64KY64iIIOyjvOyalOuLiOulvCDrhIjrrLTrhIjrrLQg7IKs656R7ZWY64qUIOybkO2VmOyUqOyVvA==
